services:
  meowcoin-core:
    build:
      context: .
      dockerfile: ./meowcoin-core/Dockerfile
      args:
        # For the most reliable builds, uncomment the line below and set a specific version
        # Find available versions on the Meowcoin GitHub releases page
        # MEOWCOIN_VERSION: 2.0.5
        MEOWCOIN_VERSION: ${MEOWCOIN_VERSION:-latest}
        MEOWCOIN_ARCH: ${MEOWCOIN_ARCH:-x86_64-linux-gnu}
        MEOWCOIN_UID: ${MEOWCOIN_UID:-1000}
        MEOWCOIN_GID: ${MEOWCOIN_GID:-1000}
    image: meowcoin-core:${MEOWCOIN_VERSION:-latest}
    container_name: meowcoin-node
    hostname: meowcoin-core
    restart: unless-stopped
    environment:
      # Pass config variables to the entrypoint script
      - MEOWCOIN_RPC_PORT=${MEOWCOIN_RPC_PORT:-9766}
      - MEOWCOIN_P2P_PORT=${MEOWCOIN_P2P_PORT:-8788}
      - MEOWCOIN_MAX_CONNECTIONS=${MEOWCOIN_MAX_CONNECTIONS:-100}
      - MEOWCOIN_DB_CACHE=${MEOWCOIN_DB_CACHE:-1024}
      - MEOWCOIN_MAX_MEMPOOL=${MEOWCOIN_MAX_MEMPOOL:-300}
      - MEOWCOIN_TXINDEX=${MEOWCOIN_TXINDEX:-1}
      - MEOWCOIN_MEOWPOW=${MEOWCOIN_MEOWPOW:-1}
      - MEOWCOIN_BANTIME=${MEOWCOIN_BANTIME:-86400}
      - TZ=${TZ:-UTC}
    ports:
      - "127.0.0.1:${MEOWCOIN_RPC_PORT:-9766}:${MEOWCOIN_RPC_PORT:-9766}"
      - "${MEOWCOIN_P2P_PORT:-8788}:${MEOWCOIN_P2P_PORT:-8788}"
    volumes:
      - meowcoin_data:/home/meowcoin/.meowcoin
      # Uncomment the line below to use a custom meowcoin.conf file
      # - ./path/to/your/meowcoin.conf:/home/meowcoin/.meowcoin/meowcoin.conf:ro
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "getblockchaininfo"]
      interval: 120s
      timeout: 60s
      retries: 10
      start_period: 600s
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 1024
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMIT_MEMORY:-4G}
          cpus: '${RESOURCES_LIMIT_CPUS:-2.0}'
        reservations:
          memory: ${RESOURCES_RESERVATION_MEMORY:-2G}
          cpus: '${RESOURCES_RESERVATION_CPUS:-0.5}'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  meowcoin-monitor:
    build:
      context: .
      dockerfile: ./meowcoin-monitor/Dockerfile
    image: meowcoin-monitor:latest
    container_name: meowcoin-monitor
    depends_on:
      meowcoin-core:
        condition: service_started
    restart: unless-stopped
    environment:
      - MEOWCOIN_RPC_PORT=${MEOWCOIN_RPC_PORT:-9766}
      - MONITOR_INTERVAL=${MONITOR_INTERVAL:-60}
    volumes:
      - meowcoin_data:/data:ro
    healthcheck:
      test: ["CMD", "nc", "-z", "meowcoin-core", "${MEOWCOIN_RPC_PORT:-9766}", "-w", "10"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 120s
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 64
      nofile:
        soft: 1024
        hard: 1024
    deploy:
      resources:
        limits:
          memory: ${MONITOR_LIMIT_MEMORY:-256M}
          cpus: '${MONITOR_LIMIT_CPUS:-0.2}'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge
    name: meowcoin-network

volumes:
  meowcoin_data:
    driver: local
    name: meowcoin_data
