[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:fail2ban]
command=/bin/bash -c "if [ '${ENABLE_FAIL2BAN}' = 'true' ]; then service fail2ban start; fi; sleep infinity"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=0
startretries=0
exitcodes=0
condition=true

[program:meowcoin]
command=/entrypoint.sh meowcoind
user=meowcoin
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0