#!/bin/bash

# Meowcoin Node Helper Functions
# This script contains common functions used by other scripts

# Global variables
MEOWCOIN_DATA=${MEOWCOIN_DATA:-/data}
MEOWCOIN_CONFIG=${MEOWCOIN_CONFIG:-/config}
MEOWCOIN_HOME=${HOME:-/home/meowcoin}
MEOWCOIN_CLI="/usr/local/bin/meowcoin-cli -conf=${MEOWCOIN_CONFIG}/meowcoin.conf"

# Logging functions
log_info() {
    echo -e "\e[32m[INFO]\e[0m $1"
}

log_warn() {
    echo -e "\e[33m[WARN]\e[0m $1"
}

log_error() {
    echo -e "\e[31m[ERROR]\e[0m $1" >&2
}

# Safely execute a command and return status
safe_exec() {
    local output
    local status=0
    
    output=$(eval "$@" 2>&1) || status=$?
    
    if [ $status -ne 0 ]; then
        log_error "Command failed: $1"
        log_error "Output: $output"
    fi
    
    return $status
}

# Get meowcoin version
get_version() {
    if [ -f "/usr/local/bin/meowcoind" ]; then
        meowcoind -version | head -n 1 | cut -d ' ' -f 1-2 || echo "Unknown"
    else
        echo "Unknown"
    fi
}

# Display ASCII banner
display_banner() {
    local text="$1"
    local width=$(( ${#text} + 4 ))
    
    echo ""
    printf "%0.s=" $(seq 1 $width)
    echo ""
    echo "  $text"
    printf "%0.s=" $(seq 1 $width)
    echo ""
}

# Display help information
display_help() {
    echo "Meowcoin Node Container Help"
    echo "============================"
    echo "Available commands:"
    echo "  cli [args]  - Run meowcoin-cli with arguments"
    echo "  shell       - Start a shell session"
    echo "  help        - Display this help message"
    echo ""
    echo "Environment variables:"
    echo "  MEOWCOIN_DATA=/data           - Data directory"
    echo "  MEOWCOIN_CONFIG=/config       - Configuration directory"
    echo "  MEOWCOIN_MODE=full            - Node operation mode (full, minimal)"
    echo "  SYSTEM_MEMORY=auto            - System memory allocation"
    echo "  MAX_CONNECTIONS=auto          - Maximum connections"
    echo "  ENABLE_TXINDEX=1              - Enable transaction index"
    echo "  AUTO_UPDATE=security          - Auto-update mode (none, security, all)"
    echo "  BACKUP_ENABLED=true           - Enable automatic backups"
    echo "  BACKUP_INTERVAL=daily         - Backup interval (hourly, daily, weekly)"
    echo ""
}

# Display connection information
display_access_info() {
    log_info "Meowcoin node access information:"
    echo "=================================================="
    echo "RPC Port: 9766"
    echo "P2P Port: 8788"
    echo "Web UI: http://localhost:8080"
    echo "=================================================="
}

# Apply custom configuration if exists
apply_custom_config() {
    local custom_conf="${MEOWCOIN_CONFIG}/custom.conf"
    local target_conf="${MEOWCOIN_CONFIG}/meowcoin.conf"
    
    # Create default config if it doesn't exist
    if [ ! -f "$target_conf" ]; then
        log_info "Creating default configuration file"
        
        # Create minimal configuration with secure defaults
        cat > "$target_conf" << EOF
# Meowcoin Node Configuration
# Auto-generated by container startup script

# Network
listen=1
server=1
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
rpcbind=0.0.0.0:9766

# Security
rpcauth=$(generate_rpc_auth)

# Performance
dbcache=450
maxmempool=300
maxconnections=50

# Features
txindex=1
EOF
    fi
    
    # Apply custom config if it exists
    if [ -f "$custom_conf" ]; then
        log_info "Applying custom configuration"
        
        # Safe merge of custom config
        while IFS= read -r line; do
            # Skip comments and empty lines
            if [[ "$line" =~ ^#.*$ ]] || [[ -z "$line" ]]; then
                continue
            fi
            
            # Extract setting name
            setting=$(echo "$line" | cut -d= -f1)
            
            # Remove existing setting if present
            if grep -q "^$setting=" "$target_conf"; then
                sed -i "/^$setting=/d" "$target_conf"
            fi
            
            # Add new setting
            echo "$line" >> "$target_conf"
        done < "$custom_conf"
    fi
}

# Generate secure RPC authentication credentials
generate_rpc_auth() {
    local rpc_user="meowcoin"
    local rpc_password=$(dd status=none bs=20 count=1 if=/dev/urandom | md5sum | awk '{print $1}')
    local salt=$(dd status=none bs=16 count=1 if=/dev/urandom | md5sum | awk '{print $1}')
    
    # Save credentials to a file for the backend to use
    echo "$rpc_user:$rpc_password" > "${MEOWCOIN_DATA}/.meowcoin/rpc.pass"
    chmod 600 "${MEOWCOIN_DATA}/.meowcoin/rpc.pass"
    
    # Return rpcauth line for config
    python3 -c "import hmac, hashlib; print('$rpc_user:' + hmac.new(b'$salt', b'$rpc_password', hashlib.sha256).hexdigest() + ':$salt')"
}

# Create backup of blockchain data
create_backup() {
    local backup_dir="${MEOWCOIN_DATA}/backups"
    local timestamp=$(date +"%Y%m%d_%H%M%S")
    local backup_file="${backup_dir}/meowcoin_backup_${timestamp}.tar.gz"
    
    # Ensure backup directory exists
    mkdir -p "$backup_dir"
    
    log_info "Creating backup: $backup_file"
    
    # Stop services before backup if needed
    if [ "$1" = "with-stop" ]; then
        gosu meowcoin $MEOWCOIN_CLI stop
        sleep 10
    fi
    
    # Create compressed backup
    tar -czf "$backup_file" -C "${MEOWCOIN_DATA}" .meowcoin
    
    # Restart services if they were stopped
    if [ "$1" = "with-stop" ]; then
        gosu meowcoin meowcoind -conf="${MEOWCOIN_CONFIG}/meowcoin.conf" -daemon
    fi
    
    log_info "Backup completed successfully"
    
    # Clean up old backups (keep last 5)
    find "$backup_dir" -name "meowcoin_backup_*.tar.gz" -type f -printf '%T@ %p\n' | \
        sort -n | head -n -5 | cut -d' ' -f2- | xargs -r rm
    
    return 0
}

# Function to check system health
check_health() {
    # Check if meowcoind process is running
    if ! pgrep -x "meowcoind" > /dev/null; then
        log_error "Meowcoin daemon is not running"
        return 1
    fi
    
    # Check if backend server is running
    if ! pgrep -f "node.*dist/index.js" > /dev/null; then
        log_warn "Backend server is not running"
    fi
    
    # Try to get blockchain info
    if ! gosu meowcoin $MEOWCOIN_CLI getblockchaininfo &>/dev/null; then
        log_error "Meowcoin RPC is not responding"
        return 1
    fi
    
    return 0
}