version: '3.8'

# Advanced Meowcoin Node Setup
# This example provides a full-featured configuration with monitoring

services:
  meowcoin-core:
    build:
      context: ../../
      dockerfile: ./docker/core/Dockerfile
      args:
        MEOWCOIN_VERSION: ${MEOWCOIN_VERSION:-latest}
        MEOWCOIN_ARCH: ${MEOWCOIN_ARCH:-x86_64-linux-gnu}
        MEOWCOIN_UID: ${MEOWCOIN_UID:-1000}
        MEOWCOIN_GID: ${MEOWCOIN_GID:-1000}
    image: ${DOCKER_REGISTRY:-local}/meowcoin-core:${MEOWCOIN_VERSION:-latest}
    container_name: meowcoin-node
    hostname: meowcoin-core
    restart: unless-stopped
    environment:
      - MEOWCOIN_RPC_PORT=9766
      - MEOWCOIN_P2P_PORT=8788
      - MEOWCOIN_MAX_CONNECTIONS=100
      - MEOWCOIN_DB_CACHE=2048
      - MEOWCOIN_MAX_MEMPOOL=500
      - MEOWCOIN_TXINDEX=1
      - MEOWCOIN_MEOWPOW=1
      - MEOWCOIN_BANTIME=86400
      - TZ=UTC
    ports:
      - "127.0.0.1:9766:9766"  # RPC port (local access only)
      - "8788:8788"            # P2P port
    volumes:
      - meowcoin_data:/home/meowcoin/.meowcoin
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 1024
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  meowcoin-monitor:
    build:
      context: ../../
      dockerfile: ./docker/monitor/Dockerfile
    image: ${DOCKER_REGISTRY:-local}/meowcoin-monitor:${MEOWCOIN_VERSION:-latest}
    container_name: meowcoin-monitor
    depends_on:
      meowcoin-core:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - MEOWCOIN_RPC_PORT=9766
      - MEOWCOIN_HOST=meowcoin-core
      - MONITOR_INTERVAL=180
      - TZ=UTC
    volumes:
      - meowcoin_data:/data:ro
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 64
      nofile:
        soft: 1024
        hard: 1024
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: meowcoin-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "127.0.0.1:9090:9090"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: meowcoin-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=meowcoin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "127.0.0.1:3000:3000"
    read_only: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  default:
    driver: bridge
    name: meowcoin-network
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  meowcoin_data:
    driver: local
    name: meowcoin_data
  prometheus_data:
    driver: local
    name: meowcoin_prometheus_data
  grafana_data:
    driver: local
    name: meowcoin_grafana_data