version: '3.8'

# Basic Meowcoin Node Setup
# This example provides a minimal configuration for running a Meowcoin node

services:
  meowcoin-core:
    build:
      context: ../../
      dockerfile: ./docker/core/Dockerfile
      args:
        MEOWCOIN_VERSION: ${MEOWCOIN_VERSION:-latest}
        MEOWCOIN_ARCH: ${MEOWCOIN_ARCH:-x86_64-linux-gnu}
    image: ${DOCKER_REGISTRY:-local}/meowcoin-core:${MEOWCOIN_VERSION:-latest}
    container_name: meowcoin-node
    restart: unless-stopped
    environment:
      - MEOWCOIN_RPC_PORT=9766
      - MEOWCOIN_P2P_PORT=8788
      - MEOWCOIN_MAX_CONNECTIONS=50
      - MEOWCOIN_DB_CACHE=512
      - MEOWCOIN_MAX_MEMPOOL=200
      - MEOWCOIN_TXINDEX=1
    ports:
      - "127.0.0.1:9766:9766"  # RPC port (local access only)
      - "8788:8788"            # P2P port
    volumes:
      - meowcoin_data:/home/meowcoin/.meowcoin
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

volumes:
  meowcoin_data:
    driver: local